# Generated by Django 3.2.25 on 2025-02-14 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='actualizado_en',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='evento',
            name='cambios',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
