# Generated by Django 3.2.25 on 2025-02-14 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20250214_1046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='actualizado_en',
            field=models.DateField(auto_now=True),
        ),
    ]
