# Generated by Django 3.2.25 on 2025-02-14 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_evento_actualizado_en'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='actualizado_en',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
