# Generated by Django 3.2.25 on 2025-02-25 16:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_evento_actualizado_en'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='departamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.direccion', verbose_name='departamento'),
        ),
    ]
