# Generated by Django 3.2.25 on 2025-11-05 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='flayer',
            field=models.FileField(blank=True, null=True, upload_to='flayers/'),
        ),
    ]
