# Generated by Django 3.2.25 on 2025-05-26 19:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArchivoExcel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to='excels/')),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('nombre_original', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folio', models.IntegerField(blank=True, null=True)),
                ('nombre', models.CharField(blank=True, max_length=100, null=True)),
                ('figura', models.CharField(blank=True, max_length=90, null=True)),
                ('actividad', models.CharField(blank=True, max_length=255, null=True)),
                ('periodo', models.CharField(blank=True, max_length=255, null=True)),
                ('autoridad_uno', models.CharField(blank=True, max_length=255, null=True)),
                ('autoridad_dos', models.CharField(blank=True, max_length=255, null=True)),
                ('archivo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='folios.archivoexcel')),
            ],
        ),
    ]
