# Generated by Django 3.2.25 on 2025-07-29 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('folios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='folio',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
