# Generated by Django 3.2.25 on 2025-08-28 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('folios', '0002_alter_producto_folio'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='autoridad_tres',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
