# Generated by Django 3.2.25 on 2025-12-16 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('folios', '0003_producto_autoridad_tres'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='nombre',
            field=models.TextField(blank=True, null=True),
        ),
    ]
